### ISSUE TITLE
help

### ISSUE THREAD

**Issue by noobsohail** [pseudosavant/player.html#15]
can you help us to integrate your mkv player in indinaime.com (wordpress) + support videos from links

**Comment by pseudosavant** [comment]
This player isn't designed to be implemented within another app/site like Wordpress. It is just a standalone app.

You may be able to get it to work in an `<iframe>` however. It just uses the browser's playback engine, so you should be able to just use `<video>` in your HTML instead of trying to use something like `player.html`.
