### ISSUE TITLE
Firefox Thumbnail support

### ISSUE THREAD

**Issue by ubergesundheit** [pseudosavant/player.html#5]
Very nice project! I just tried this in Firefox 80.0.1 which [does not support the `options` parameter for `createImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap#Browser_compatibility) which seems to be used for thumbnail generation.

Do you think there is maybe a way around this? Or could the `canThumbnail` functionality availabiltiy expanded to disable thumbnail generation on Firefox?

**Comment by pseudosavant** [comment]
I'll check it out. I'm sure it can be worked around. The only critical parameter being passed in in the options is the resize width and that can be done as a function argument. It used to use `canvas.drawImage()` for that but `createImageBitmap` is more efficient. I bet I hadn't noticed because the thumbnails were all cached already in my Firefox.

**Comment by pseudosavant** [comment]
It was pretty easy to fix. I committed the change to master. https://github.com/pseudosavant/player.html/commit/3e20e6c5fea67cb08ace567f2107dffd341b2cbf

**Comment by ubergesundheit** [comment]
Very nice! Thank you very much!
